// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface SnailDetails {
  data: Data;
}

export interface Data {
  snail_promise: SnailPromise;
}

export interface SnailPromise {
  id: number;
  klass: string;
  generation: number;
  adaptations: string[];
  purity: number;
  gender: Gender;
  name: string;
  genome: string[];
  family: string;
  image: string;
  owner: string;
  holder: string;
  market: Market;
  gene_market: null;
  stats: Stats;
  visuals: Visual[];
  more_stats: any[];
  __typename: string;
}

export interface Gender {
  value: string;
  id: number;
  __typename: string;
}

export interface Market {
  price: number;
  item_id: number;
  price_wei: string;
  on_sale: boolean;
  last_sale: number;
  highest_sale: number;
  __typename: string;
}

export interface Stats {
  races: number;
  elo: string;
  earned_avax: number;
  earned_token: number;
  win_ratio: string;
  top_three_ratio: string;
  experience: Experience;
  __typename: string;
}

export interface Experience {
  xp: number;
  level: number;
  on: number;
  remaining: number;
  reward: number;
  __typename: string;
}

export interface Visual {
  trait_type: string;
  value: string;
  count: number;
  percentage: number;
  __typename: string;
}
