// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface Marketplace {
  data: Data;
}

export interface Data {
  marketplace_promise: MarketplacePromise;
}

export interface MarketplacePromise {
  snails: Snail[];
  count: number;
  __typename: string;
}

export interface Snail {
  id: number;
  adaptations: string[];
  name: string;
  image: string;
  market: Market;
  __typename: SnailTypename;
}

export enum SnailTypename {
  Snail = 'Snail',
}

export interface Market {
  price: number;
  item_id: number;
  on_sale: boolean;
  price_wei: string;
  __typename: MarketTypename;
}

export enum MarketTypename {
  MarketListing = 'MarketListing',
}
